spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}/${BASEDNAME}
    username: ${USERNAME}
    password: ${BASEPASSWORD}

server:
  error:
    include-stacktrace: never


api:
  security:
    secret: ${APISECURITYSECRET}